-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 16:30:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salesmate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salesmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salesmate` DEFAULT CHARACTER SET utf8 ;
USE `salesmate` ;

-- -----------------------------------------------------
-- Table `salesmate`.`NewClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesmate`.`NewClient` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `clientName` VARCHAR(100) NULL,
  `clientDomain` VARCHAR(50) NULL,
  `location` VARCHAR(100) NULL,
  `itemCategory` VARCHAR(100) NULL,
  `publisher` VARCHAR(50) NULL,
  `status` VARCHAR(45) NULL,
  `NewClientcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salesmate`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesmate`.`payment` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `accumulateFee` INT ZEROFILL NULL,
  `onetimeFee` INT ZEROFILL NULL,
  `NewClient_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  INDEX `fk_payment_NewClient_idx` (`NewClient_idx` ASC),
  CONSTRAINT `fk_payment_NewClient`
    FOREIGN KEY (`NewClient_idx`)
    REFERENCES `salesmate`.`NewClient` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
