-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 16:06:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salesmate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salesmate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salesmate` DEFAULT CHARACTER SET utf8 ;
USE `salesmate` ;

-- -----------------------------------------------------
-- Table `salesmate`.`NewClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salesmate`.`NewClient` (
  `idx` INT NOT NULL,
  `clientName` VARCHAR(100) NULL,
  `clientDomain` VARCHAR(50) NULL,
  `location` VARCHAR(100) NULL,
  `itemCategory` VARCHAR(100) NULL,
  `publisher` VARCHAR(50) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
